application: project
version: 1
runtime: python27
api_version: 1
threadsafe: yes

builtins:
- remote_api: on

handlers:
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: favicon\.ico

- url: /_ah/(mapreduce|queue|warmup|start|stop).*
  script: project.wsgi.application
  secure: always
  login: admin

- url: /_ah/internalupload.*
  script: project.wsgi.application
  secure: always

- url: /static
  static_dir: static/
  secure: always

- url: /.*
  script: project.wsgi.application
  secure: optional
